apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Build and run Scala and Java applications using SBT
    iconClass: icon-scala
    openshift.io/display-name: SBT
  generation: 4
  name: sbt
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Scala and Java applications using SBT
      iconClass: icon-scala
      openshift.io/display-name: SBT
      openshift.io/provider-display-name: https://github.com/jw3/sbt-s2i
      sampleRepo: https://github.com/theiterators/akka-http-microservice
      supports: sbt:0.13.15,java,scala
      tags: builder,java,scala
      version: "0.13.15"
    from:
      kind: DockerImage
      name: jwiii/sbt-s2i:0.13.15-2.12.3
    generation: 1
    importPolicy: {}
    name: "0.13.15"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Scala and Java applications using SBT 0.13
      iconClass: icon-scala
      openshift.io/display-name: SBT
      openshift.io/provider-display-name: https://github.com/jw3/sbt-s2i
      sampleRepo: https://github.com/theiterators/akka-http-microservice
      supports: sbt:0.13.16,java,scala
      tags: builder,java,scala
      version: "0.13.16"
    from:
      kind: DockerImage
      name: jwiii/sbt-s2i:0.13.16-2.12.3
    generation: 1
    importPolicy: {}
    name: "0.13.16"
    referencePolicy:
      type: Source
